blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/yourusername/eyebreak/discussions/new?category=q-a
    about: Ask questions and discuss ideas with the community
  - name: 💡 Feature Ideas
    url: https://github.com/yourusername/eyebreak/discussions/new?category=ideas
    about: Share and discuss new feature ideas
  - name: 🆘 Get Help
    url: https://github.com/yourusername/eyebreak/discussions/new?category=help
    about: Get help with installation or usage
